export default {
    UPDATE_CASE_FILTER: 'UPDATE_CASE_FILTER',
    REQUEST_STATES: 'REQUEST_STATES',
    RECEIVE_STATES: 'RECEIVE_STATES',
    REQUEST_CASES: 'REQUEST_CASES',
    RECEIVE_CASES: 'RECEIVE_CASES',
}